### ISSUE TITLE
Expose all receiving gateways

### ISSUE THREAD

**Issue by gonzalocasas** [TheThingsNetwork/sdk#15]
It looks like the node.js client is only emitting the first object in the metadata array:
https://github.com/TheThingsNetwork/sdk/blob/master/apps/node/ttn/src/client.js#L45

I guess that's because the first object is the "best gateway". But there are situations in which we might want to use the rest of the metadata (like mapping coverage, for instance).

Could we emit the rest as well? Will the rest really contain all other gateways?

**Comment by johanstokking** [comment]
It takes the first gateway indeed. What our refactored back-end will do is return one metadata object with the fields from the device (e.g. frequency, frame count, port, etc), containing an array of objects with the fields from the gateways (signal strength, time, location, etc).

So to be as forward-compatible as possible, we have one object here, and its format will remain like this as much as possible, but we add an array with metadata fields from the other gateways.
